- name: Stop pf
  ansible.builtin.service:
    name: pf
    status: "stopped"

- name: Check if in domain
  ansible.builtin.shell: command -v adcli
  ignore_errors: true
  register: adcli

- name: Insert rules in dc conf file
  when: adcli.rc == 0
  ansible.builtin.blockinfile:
    path: /root/dc_blackout.conf
    block: |
      pass out inet proto tcp from any to any port 80 keep state
      pass out inet proto tcp from any to any port 443 keep state
      pass out inet proto udp from any to any port 53 keep state

- name: Insert rules in conf file
  when: not adcli.rc == 0
  ansible.builtin.blockinfile:
    path: /root/blackout.conf
    block: |
      pass out inet proto tcp from any to any port 80 keep state
      pass out inet proto tcp from any to any port 443 keep state
      pass out inet proto udp from any to any port 53 keep state

- name: Start pf
  ignore_unreachable: true
  ansible.builtin.service:
    name: pf
    status: "started"

- name: Install wazuh
  ansible.builtin.package:
    name: "wazuh-agent"
    state: "present"

- name: Add manager IP
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "IP"
    replace: "{{ manager_ip }}"

- name: Add hostname
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "</server>"
    replace: "</server>\n    <enrollment>\n      <agent_name>{{ inventory_hostname }}</agent_name>\n    </enrollment>"

- name: Check ossec.conf for audit.log
  ansible.builtin.command: grep -Fq 'audit.log' /var/ossec/etc/ossec.conf
  register: grep_ossec_conf
  failed_when: false
  changed_when: false

- name: Edit ossec conf file with audit
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    block: |
      <ossec_config>
        <localfile>
          <log_format>audit</log_format>
          <location>/var/log/audit/audit.log</location>
        </localfile> 

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/output.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/input.log</location>
        </localfile>
      </ossec_config>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  when: not grep_ossec_conf.rc == 0

- name: Edit ossec conf file without audit
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    block: |
      <ossec_config>
        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/output.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/input.log</location>
        </localfile>
      </ossec_config>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  when: grep_ossec_conf.rc == 0

- name: start wazuh agent
  ansible.builtin.shell: /var/ossec/bin/wazuh-control start

- name: Stop pf
  ansible.builtin.service:
    name: pf
    status: "stopped"

- name: Insert rules in dc conf file
  when: adcli.rc == 0
  ansible.builtin.blockinfile:
    path: /root/dc_blackout.conf
    state: absent
    block: |
      pass out inet proto tcp from any to any port 80 keep state
      pass out inet proto tcp from any to any port 443 keep state
      pass out inet proto udp from any to any port 53 keep state

- name: Insert rules in conf file
  when: not adcli.rc == 0
  ansible.builtin.blockinfile:
    path: /root/blackout.conf
    state: absent
    block: |
      pass out inet proto tcp from any to any port 80 keep state
      pass out inet proto tcp from any to any port 443 keep state
      pass out inet proto udp from any to any port 53 keep state

- name: Start pf
  ignore_unreachable: true
  ansible.builtin.service:
    name: pf
    status: "started"
