- name: Import gpg key
  ansible.builtin.rpm_key:
    key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: present

- name: Add repository
  ansible.builtin.blockinfile:
    path: "/etc/yum.repos.d/wazuh.repo"
    create: true
    block: |
      [wazuh]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=EL-$releasever - Wazuh
      baseurl=https://packages.wazuh.com/4.x/yum/
      protect=1

- name: install client
  ansible.builtin.yum:
    name: wazuh-agent
    state: present

- name: Add manager IP
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "MANAGER_IP"
    replace: "{{ manager_ip }}"

- name: add hostname
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    insertafter: "<client>"
    block: |
        <enrollment>
          <agent_name>{{ inventory_hostname }}</agent_name>
        </enrollment>
  notify: "start/enable wazuh-agent"

