# Implement Network Blackout with IPTables

- name: flush current rules
  ansible.builtin.iptables:
    flush: true
    chain: "{{ item }}"
  with_items: ["INPUT", "OUTPUT"]

- name: Add cron to flush rules just in case
  ansible.builtin.cron:
    name: "Flush Firewall"
    minute: "*/5"
    job: "iptables -F"

- name: Add invalid packet rule
  ansible.builtin.iptables:
    chain: "{{ item }}"
    cstate: ["INVALID"]
    jump: "DROP"
  with_items: ['INPUT', 'OUTPUT']

- name: Add localhost INPUT rule
  ansible.builtin.iptables:
    chain: "INPUT"
    source: "127.0.0.0/8"
    jump: "ACCEPT"

- name: Add localhost OUTPUT rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    destination: "127.0.0.0/8"
    jump: "ACCEPT"

- name: Add ICMP INPUT rule
  ansible.builtin.iptables:
    chain: "INPUT"
    protocol: "icmp"
    jump: "ACCEPT"

- name: Add ICMP OUTPUT rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    protocol: "icmp"
    jump: "ACCEPT"

- name: use iptables to only allow team IPs into network
  ansible.builtin.iptables:
    action: "append"
    chain: "INPUT"
    destination_port: "22"
    source: "{{ item }}"
    jump: "ACCEPT"
    protocol: "tcp"
    state: "present"
  loop: "{{ team_ips }}"

- name: use iptables to only let established ssh out
  ansible.builtin.iptables:
    action: "append"
    chain: "OUTPUT"
    source_port: "22"
    jump: "ACCEPT"
    protocol: "tcp"
    cstate: ["ESTABLISHED"]
    state: "present"

- name: Add dropped INPUT LOG rule
  ansible.builtin.iptables:
    chain: "INPUT"
    jump: "LOG"
    log_prefix: "[DROPPED_INPUT] "

- name: Add dropped OUTPUT LOG rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    jump: "LOG"
    log_prefix: "[DROPPED_OUTPUT] "

- name: Add default drop rule
  ansible.builtin.iptables:
    chain: "{{ item }}"
    jump: "DROP"
  with_items: ['INPUT', 'OUTPUT']
