# Do a network blackout on linux

- name: Blackout on Linux
  become: true
  when: ansible_system | lower == "linux"
  block:
    - name: install iptables if not present
      ansible.builtin.package:
        name: iptables
        state: present

    - name: Do stuff with iptables
      include_tasks: iptables.yaml

- name: Blackout on windows
  when: ansible_os_family | lower == "windows"
  become: true
  become_method: runas
  become_user: Administrator
  block:
    - include_tasks: windows.yaml
