
linux:
  hosts:
    alpine:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
    centos:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
    debian:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
    bsd:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
    suse:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
    ubuntu:
      ansible_host: nn
      ansible_user: n
      ansible_password: Is1WaterWet?
    dash:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
windows:
  hosts:
    win2016:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
      ansible_connection: "winrm"
      ansible_winrm_scheme: "http"
      ansible_port: "5985"
      ansible_winrm_transport: "ntlm"
      domain_controller: n
    win2019:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
      ansible_connection: "winrm"
      ansible_winrm_scheme: "http"
      ansible_port: "5985"
      ansible_winrm_transport: "ntlm"
      domain_controller: n
manager:
  hosts:
    dash:
      ansible_host: n
      ansible_user: n
      ansible_password: Is1WaterWet?
