# Setup Ansible to run on windows

- name: Windows Setup
  strategy: free
  hosts: Windows
  gather_facts: no
  tasks:
    - name: Install python
      ansible.builtin.script: python.ps1

    - name: Optimize powershell
      ansible.builtin.script: optimize.ps1
