- name: Install on Non-Windows machines
  hosts: all,!windows,!manager
  become: yes
  roles:
    - linux_agent
  tags:
    - linux

- name: Install on Windows machines
  hosts: windows
  strategy: free
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
    - win_agent
  tags:
    - windows
 
- name: Install the manager
  hosts: manager
  become: yes
  roles:
    - manager
  tags:
    - manager
