- name: Install on Non-Windows machines
  hosts: all,!windows,!manager
  become: yes
  roles:
    - linux_agent
  tags:
    - linux

- name: Install on Windows machines
  hosts: windows
  become: yes
  become_method: Runas
