- name: Install on Linux machines
  hosts: linux
  strategy: free
  become: yes
  roles:
    - linux_agent
  tags:
    - linux

- name: Install on Windows machines
  hosts: windows
  strategy: free
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
    - win_agent
  tags:
    - windows

- name: Install on Solaris machines
  hosts: solaris
  strategy: free
  become: yes
  roles:
    - solaris_agent
  tags:
    - solaris

- name: Install on BSD machines
  hosts: bsd
  become: yes
  roles:
    - bsd_agent
  tags:
    - bsd
 
- name: Install the manager
  hosts: manager
  become: yes
  roles:
    - manager
  tags:
    - manager
