- name: Enable internet access
  community.windows.win_firewall_rule:
    group: "Internet"
    enabled: true

- name: Download and install msi for wazuh
  ansible.windows.win_package:
    path: "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.2-1.msi"
    arguments: >-
      /q
      WAZUH_MANAGER={{ manager_ip }}
      WAZUH_AGENT_NAME={{ inventory_hostname }}

- name: Start and enable wazuh
  ansible.windows.win_service:
    name: Wazuh
    state: "started"

- name: Add wazuh rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow the wazuh-agent to communicate with the manager"
    direction: "out"
    group: "Wazuh"
    name: "Wazuh to manager"
    remote_ip: "{{ manager_ip }}"
    remote_port: "1514,1515"
    protocol: "tcp"

- name: Disable internet access
  community.windows.win_firewall_rule:
    group: "Internet"
    enabled: false
